#include "main.h"

#include <stdio.h>
#include <stdlib.h>
#include "images/Sunflower.h"
#include "images/Background.h"
#include "images/Dog1.h"
#include "images/startScreen.h"
#include "images/loseScreen.h"
#include <string.h>

#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  START_HELPER,
  PLAY,
  LOSE,
  LOSE_HELPER,
};

DOG dog;
SUNFLOWER *flower;
SUNFLOWER *currentFlower;
SUNFLOWER *nextFlower;
const int flowerDistance = 100;

const int jump = 70;
const int flowerSpeed = 3;
const int numSunflowers = 1;



int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state

  REG_DISPCNT = MODE3 | BG2_ENABLE;
  enum gba_state state = START;

  //drawFullScreenImageDMA(Background);

  int start = 0;
  int up = 0;
  int select = 0;

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons
    

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    waitForVBlank();
    switch (state) {
      case START:

        reset();
        state = START_HELPER;
        drawFullScreenImageDMA(Start_Screen);
        drawSunflower();
        drawDog();
        
        break;

      case START_HELPER:
        if (KEY_DOWN(BUTTON_START, previousButtons) && !up) {
                    drawFullScreenImageDMA(Background);
                    state = PLAY;
                }
        break;

      case PLAY:

        if (!isAlive() && !KEY_DOWN(BUTTON_A, previousButtons)) {
          state = LOSE;
          break;
        }
        
        dog.row = HEIGHT - DOG1_HEIGHT - 13;
        undrawFlowers();
        moveFlower();
        if (KEY_DOWN(BUTTON_UP, BUTTONS)) {
          if (up) {
            dog.row -= jump;
            undrawImageDMA(dog.row + jump, dog.col, DOG1_WIDTH, DOG1_HEIGHT, Background);
            drawDog();
          }
        }

        if (KEY_DOWN(BUTTON_SELECT, currentButtons) && !select) {
          drawFullScreenImageDMA(Background);
          state = START;
          break;
        }
        
        drawSunflower();
        undrawImageDMA(dog.row - jump, dog.col, DOG1_WIDTH, DOG1_HEIGHT, Background);
        drawDog();
        break;

      case LOSE:
        drawFullScreenImageDMA(Lose_Screen);
        char string[5];
        sprintf(string, "%d", vBlankCounter);
        drawString(40, 150, string, BLACK);
        drawString(150, (WIDTH - getStringWidth("Press START to restart")) / 2, "Press START to restart", BLACK);
        state = LOSE_HELPER;

        break;

      case LOSE_HELPER:
      if (KEY_DOWN(BUTTON_START, BUTTONS) && !start) {
          state = START;
      }
      break;

      }

        if (KEY_DOWN(BUTTON_START, currentButtons)) {
            start = 1;
        } else {
            start = 0;
        }
        if (KEY_DOWN(BUTTON_UP, currentButtons)) {
            up = 1;
        } else {
            up = 0;
        }
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
            select = 1;
        } else {
            select = 0;
        }

    previousButtons = currentButtons; // Store the current state of the buttons
  }
}

  //UNUSED((previousButtons)); // You can remove this once previousButtons is used

  // reset the status of the game
  void reset(void) {
    
    flower = malloc(sizeof(SUNFLOWER) * numSunflowers);
    currentFlower = flower;

    generateSunflowers();

    dog.col = 10;
    dog.row = HEIGHT - DOG1_HEIGHT - 13; // bottom of dog is 13 pixels from the bottom of the screen
}

  // make sunflower visible
  void sunflowerSetVisible(SUNFLOWER *sunflower) {
    sunflower->visible = 1;
    sunflower->col = WIDTH - SUNFLOWER_WIDTH - 1;
    sunflower->row = HEIGHT - SUNFLOWER_HEIGHT - 12; // bottom of sunflower is 12 pixels from the bottom of the screen
  }

  // initiate flower data
  void generateSunflowers(void) {
    sunflowerSetVisible(flower);
    for (int i = 1; i < numSunflowers; ++i) {
        flower[i].visible = 0;
        flower[i].col = flower[0].col + i * flowerDistance;
    }
}

  void drawSunflower(void) {
    for (int i = 0; i < numSunflowers; i++) {
        drawSunflowerHelper(flower + i);
    }
  }

  void drawSunflowerHelper(SUNFLOWER *sunflower) {
    if (!sunflower->visible) {
        return;
    }
    if (sunflower->col < 0) {
        for (int i = 0; i < HEIGHT - SUNFLOWER_HEIGHT - 12; i++) {
            drawImageAtCol(HEIGHT - SUNFLOWER_HEIGHT - 12, -1, -sunflower->col -1, SUNFLOWER_WIDTH, SUNFLOWER_HEIGHT,
                              Sunflower);
        }
        drawImageAtCol(HEIGHT - SUNFLOWER_HEIGHT - 12, 0, -sunflower->col, SUNFLOWER_WIDTH, SUNFLOWER_HEIGHT,
                          Sunflower);
    } else {
        for (int i = 0; i < HEIGHT - SUNFLOWER_HEIGHT - 12; i++) {
            drawImageDMA(HEIGHT - SUNFLOWER_HEIGHT - 12, sunflower->col + 1, SUNFLOWER_WIDTH, SUNFLOWER_HEIGHT, Sunflower);
        }
        drawImageDMA(HEIGHT - SUNFLOWER_HEIGHT - 12, sunflower->col, SUNFLOWER_WIDTH, SUNFLOWER_HEIGHT, Sunflower);
    }

}

  // draw the dog
  void drawDog(void) {
  
    drawImageDMA(dog.row, dog.col, DOG1_WIDTH, DOG1_HEIGHT, Dog1);
  }

  // undraw flowers
  void undrawFlowers(void) {
    for (int i = 0; i < numSunflowers; ++i) {
        undrawFlowersHelper(flower + i, Background);
    }
  }

  // undraw flower rear 
  void undrawFlowersHelper(SUNFLOWER *sun, const u16 *image) {
    if (!sun->visible) {
        return;
    }
    for (int i = 0; i < SUNFLOWER_HEIGHT; i++) {
        undrawImageDMA(HEIGHT - SUNFLOWER_HEIGHT - 12, sun->col + SUNFLOWER_WIDTH, flowerSpeed + 1, SUNFLOWER_HEIGHT, image);
    }
    undrawImageDMA(HEIGHT - SUNFLOWER_HEIGHT - 12, sun->col - 1, flowerSpeed, SUNFLOWER_HEIGHT, image);
    for (int i = 0; i < HEIGHT - SUNFLOWER_HEIGHT - 12; i++) {
        undrawImageDMA(HEIGHT - SUNFLOWER_HEIGHT - 12, sun->col + SUNFLOWER_WIDTH - 1,
                     flowerSpeed + 1, SUNFLOWER_HEIGHT, image);
    }
  }

  // moves the sunflowers
  void moveFlower(void) {
    if (nextFlower != NULL && currentFlower->col + SUNFLOWER_WIDTH < 0) {
        free(flower);
        flower = nextFlower;
        currentFlower = nextFlower;
        generateSunflowers();
        nextFlower = NULL;
    }
    for (int i = 0; i < numSunflowers; i++) {
        flower[i].col -= flowerSpeed;
        if (flower[i].col < WIDTH - SUNFLOWER_WIDTH && flower[i].col + SUNFLOWER_WIDTH > 0) {
            flower[i].visible = 1;
        } else {
            flower[i].visible = 0;
        }
        if (flower[i].col <= dog.col + DOG1_WIDTH) {
            if (i == numSunflowers - 1) {
                nextFlower = malloc(sizeof(SUNFLOWER) * numSunflowers);
            } else {
                nextFlower = NULL;
            }
            if (currentFlower != flower + i) {
            }
            currentFlower = flower + i;
        }
    }
  }



  // detect if dog collided with flower
  int checkCollision(DOG *doggy, SUNFLOWER *sunny) {
    if (doggy->row < sunny->row) {
        return 0;
    } else {
        if ((doggy->col + DOG1_WIDTH) < sunny->col || doggy->col > sunny->col + SUNFLOWER_WIDTH) {
            return 0;
        } else {
            return 1;
        }
    }
  }


  // check if we survived
  int isAlive(void) {
    return !checkCollision(&dog, currentFlower) && dog.row < HEIGHT;
  }

  int getStringWidth(char *string) {
    return (int) ((strlen(string) - 1) * 6);
    }
